/* Set image path for ODS */
ODS LISTING GPATH="C:\Users\Kyle McLester\Desktop\dsba-6201\project-02\images\ODS_PLOTS";

/* Enable ODS Graphics */
ODS GRAPHICS ON;

/* univariate analysis */
PROC UNIVARIATE data=DATA.CATALOG2010 NORMAL PLOT;
	var RESPOND ACTBUY BUYPROP CATALOGCNT DAYLAST DOLINDEA DOLINDET DOLL24 DOLNETDA DOLNETDT DTBUYLST DTBUYORG FREQPRCH MONLAST ORDERSIZE TENURE;
run;

PROC CORR DATA=DATA.CATALOG2010 COV PLOTS=MATRIX;
	var RESPOND ACTBUY BUYPROP CATALOGCNT DAYLAST DOLINDEA DOLINDET DOLL24 DOLNETDA DOLNETDT DTBUYLST DTBUYORG FREQPRCH MONLAST ORDERSIZE TENURE;
run;
